### ISSUE TITLE
Error on startup : Unexpected token import

### ISSUE THREAD

**Issue by xstable** [nikeee/fritz-callmonitor#2]
Node: v7.2.0

If I start the example-Script you post at npm-page, I got this error:

> import { CallMonitor, EventKind } from "fritz-callmonitor";
> ^^^^^^
> SyntaxError: Unexpected token import
>     at Object.exports.runInThisContext (vm.js:78:16)
>     at Module._compile (module.js:543:28)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:420:7)
>     at startup (bootstrap_node.js:139:9)
>     at bootstrap_node.js:535:3

**Comment by xstable** [comment]
Got it... do the following steps:

1) npm install --save-dev babel-preset-es2015
2) create .babelrc in your Project-dir and put this inside: 

> { "presets": ["es2015"] }

Maybe add this information to your Readme.md

**Comment by nikeee** [comment]
You could use babel or TypeScript. The sample provided in the readme originates from TypeScript, but using babel is also valid since the sample uses no type annotations.
