### ISSUE TITLE
Changed event.kind ?!

### ISSUE THREAD

**Issue by xstable** [nikeee/fritz-callmonitor#3]
This error is thrown for Model 7490: 
> case _fritzCallmonitor.EventKind.Ring:
>                                         ^
> 
> TypeError: Cannot read property 'Ring' of undefined
>     at CallMonitor.<anonymous> (/home/suther/scripte/fritz_callMonitor/index.js:19:14)
>     at emitOne (events.js:96:13)
>     at CallMonitor.emit (events.js:188:7)
>     at CallMonitor.processLine (/home/suther/scripte/fritz_callMonitor/node_modules/fritz-callmonitor/dist/fritz-callmonitor.js:34:14)
>     at LineStream.reader.on (/home/suther/scripte/fritz_callMonitor/node_modules/fritz-callmonitor/dist/fritz-callmonitor.js:18:43)
>     at emitOne (events.js:96:13)
>     at LineStream.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:176:18)
>     at LineStream.Readable.push (_stream_readable.js:134:10)
>     at LineStream.Transform.push (_stream_transform.js:128:32)

The event seems to changed. The response of FritzBox-Callmonitor looks now like this:

> Connected to device.
> { rawData: '09.12.16 09:24:43;RING;0;017678011111;002275911111;SIP1;',
>   date: 2016-12-09T08:24:43.000Z,
>   connectionId: 0,
>   kind: 1,
>   caller: '017678011111',
>   callee: '002275911111' }
> { rawData: '09.12.16 09:24:43;RING;0;017678011111;002275911111;SIP1;',
>   date: 2016-12-09T08:24:43.000Z,
>   connectionId: 0,
>   kind: 1,
>   caller: '017678011111',
>   callee: '002275911111' }
> 017678013804 calling...
> { rawData: '09.12.16 09:24:45;DISCONNECT;0;0;',
>   date: 2016-12-09T08:24:45.000Z,
>   connectionId: 0,
>   kind: 4,
>   callDuration: 0 }
> { rawData: '09.12.16 09:24:45;DISCONNECT;0;0;',
>   date: 2016-12-09T08:24:45.000Z,
>   connectionId: 0,
>   kind: 4,
>   callDuration: 0 }
> 
So: 
kind 1 = incomming call
kind 4 = hangup by client
don't find any description what the other kind-states could be.

**Comment by nikeee** [comment]
I just pushed an update. It should be fixed in version 3.0.2. Can you confirm?
